.github/workflows/docs-update.yml
It adds an action to update the ui components docs to the developer portal
=> Add update docs action

packages/chakra-components/src/client.tsx, packages/chakra-components/src/components/Election/Election.tsx
Signer generation on Client Provider
Added CSP (oAuth) voting to the Election component
=> CSP voting

packages/chakra-components/docs/03-Election.mdx
=> Improve chakra docs

packages/rainbowkit-wallets/src/inputsWallet.ts, packages/rainbowkit-wallets/src/oAuthWallet.ts, packages/rainbowkit-wallets/src/wagmi/oAuthConnector.ts
Added types and wallet id as param
closes #93
=> New option for wallet id.

packages/chakra-components/src/components/Election/Results.tsx
=> Bugfixing the result bars in token based elections

packages/react-providers/src/election/use-election-provider.ts
closes vocdoni/ui-scaffold/issues/289
=> Prefetch of the circuits for anon. voting.

packages/react-providers/src/client/use-client-provider.ts, packages/react-providers/src/client/use-client-reducer.ts
=> Added census3 options

packages/react-providers/src/election/use-election-provider.ts
Dealing with the multiple calls errors on StrictMode using hooks
=> Preventing multiple calls to the same methods in CSP OAuth flow

mocks/handlers.ts, packages/react-providers/src/client/ClientProvider.test.tsx, packages/react-providers/src/client/use-client-provider.ts, packages/react-providers/src/client/use-client-reducer.ts, packages/react-providers/src/utils.ts, setup-tests.ts
=> Added update account functionality (and test)

packages/rainbowkit-wallets/src/components/ImportPrivateKeyModal.tsx, packages/rainbowkit-wallets/src/lib/localStorageWallet.ts
- Show a prompt requesting only the password when the private key is already stored in local storage
=> Private key wallet improvements

packages/chakra-components/src/components/Election/VoteButton.tsx, packages/chakra-components/src/i18n/locales.ts
=> Show a message instead of the vote button when election finished and user did not vote

packages/chakra-components/src/components/Election/Schedule.tsx
Fix https://github.com/vocdoni/ui-components/issues/154
=> Hide election schedule seconds

packages/chakra-components/src/components/Election/Questions.tsx, packages/chakra-components/src/i18n/locales.ts, packages/chakra-components/src/theme/index.ts, packages/chakra-components/src/theme/questions.ts
Fixes https://github.com/vocdoni/ui-scaffold/issues/622
It will need to create a new style on the ui scaffold for the new badge component
=> Improve multichoice questions

packages/chakra-components/src/components/Election/Questions.tsx, packages/chakra-components/src/components/Election/VoteButton.tsx, packages/chakra-components/src/i18n/locales.ts, packages/chakra-components/src/theme/index.ts, packages/chakra-components/src/theme/vote.ts
It helps to fix https://github.com/vocdoni/ui-scaffold/issues/532 and blocks https://github.com/vocdoni/ui-scaffold/pull/669
=> Improve weighted voting

packages/chakra-components/src/components/Election/SpreadsheetAccess.tsx
Fixes https://github.com/vocdoni/ui-components/issues/149
=> Delete PK from url on logout

packages/extended-sdk/src/client/index.ts
Some types can be improved using interfaces defined on the SDK.
=> Fix extended SDK types

packages/chakra-components/src/components/Election/Schedule.tsx, packages/chakra-components/src/i18n/locales.ts, packages/react-providers/src/organization/OrganizationProvider.tsx
=> Implement show created

packages/extended-sdk/src/client/index.ts
Expose `blockToDate` function from ChainApi
=> Implement block to date

packages/react-providers/src/election/use-election-reducer.ts
Set as draft while @selankon confirms me if I should consider abstains different here when counting votes.
=> Add participation and turnout properties

package.json, packages/chakra-components/package.json, packages/extended-sdk/package.json, packages/rainbowkit-wallets/package.json, packages/react-providers/package.json, packages/tsup.config.ts
Set as draft while I finish checking all the resulting packages.
=> Only bundle what's necessary

packages/extended-sdk/src/client/index.ts
Expose some needed account methods
=> Expose account methods

packages/extended-sdk/src/client/index.ts
It depends on https://github.com/vocdoni/vocdoni-sdk/pull/398
SDK version have be fixed when published
=> Implements txByIndex

packages/extended-sdk/src/client/index.ts
=> Delete unused argument

packages/extended-sdk/package.json, packages/extended-sdk/src/client/index.ts
=> Implement new pagination functions

packages/extended-sdk/src/client/index.ts
Use ErrBlockNotFound returned by the sdk to return back the blocks that are not found
=> Fix block not found

packages/chakra-components/src/components/Election/Envelope.tsx, packages/chakra-components/src/i18n/locales.ts, packages/chakra-components/src/theme/envelope.ts, packages/tsconfig/react-library.json
=> Prevent Envelope component to fail
